library(blorr)
library(caret)
library(descriptr)
library(dplyr)
library(ggplot2)
library(glue)
library(grid)
library(gridExtra)
library(jsonlite)
library(lubridate)
library(magrittr)
library(purrr)
library(readr)
library(readxl)
library(rlang)
library(tidyr)
library(scales)
library(shiny)
library(stats)
library(stringr)
library(tibble)
library(tools)
library(utils)

shinyServer(function(input, output, session) {
  
  
})
